name: "Qwiet preZero"
description: "Perform a Qwiet preZero Scan of your GitHub Workspace"
author: "Qwiet AI"
branding:
  icon: "shield"
  color: "blue"

inputs:
  shiftleft-access-token: 
    description: 'Qwiet preZero Authentication Token'
    required: true
  language:
    description: 'Language Code'
    required: false
  importGitHub:
    description: "Enable SARIF report generation and upload (true/false)"
    required: false
    default: "false"    
  verbose:
    description: "Enable Verbose logging"
    required: false
    default: "false"   
       

runs-on: ubuntu-latest
permissions:
  actions: read
  contents: read
  security-events: write

runs:
  using: "composite"
  steps:
  - name: Validate if token available
    if: inputs.shiftleft-access-token == ''
    shell: bash
    run: |
      echo "Qwiet Access Token is mandatory to use this action. Visit https://docs.shiftleft.io/sast/getting-started/overview for details."  
      exit 1

  - name: Validate if token available
    if: inputs.shiftleft-access-token != ''
    shell: bash
    run: |
      echo "SHIFTLEFT_ACCESS_TOKEN=${{ inputs.shiftleft-access-token }}" >> $GITHUB_ENV


  - uses: actions/checkout@v4

  - name: preZero Static Analysis
    if: inputs.verbose == 'true'
    shell: bash
    run: |
      docker run --platform linux/amd64 --rm -t --name slcore -e SHIFTLEFT_ACCESS_TOKEN="$SHIFTLEFT_ACCESS_TOKEN" -v $PWD:/app -v /tmp:/tmp shiftleft/core:latest sl analyze --verbose --app "${GITHUB_REPOSITORY_OWNER}-${GITHUB_REPOSITORY#*/}" --structured-output --structured-output-format JSON --structured-output-file-path /app/structuredOutput.json /app
    env:
      SHIFTLEFT_API_HOST: www.shiftleft.io
      SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
      SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

  - name: preZero Static Analysis
    if: inputs.verbose == 'false'
    shell: bash
    run: |
      docker run --platform linux/amd64 --rm -t --name slcore -e SHIFTLEFT_ACCESS_TOKEN="$SHIFTLEFT_ACCESS_TOKEN" -v $PWD:/app -v /tmp:/tmp shiftleft/core:latest sl analyze --app "${GITHUB_REPOSITORY_OWNER}-${GITHUB_REPOSITORY#*/}" --structured-output --structured-output-format JSON --structured-output-file-path /app/structuredOutput.json /app
    env:
      SHIFTLEFT_API_HOST: www.shiftleft.io
      SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
      SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443      
      
  - name: Generate Sarif Report
    if: inputs.importGitHub == 'true'
    shell: bash
    run: |
      chmod +x ${{ github.action_path }}/generate_sarif.sh
      ${{ github.action_path }}/generate_sarif.sh
      
  - name: Export Sarif Report to GitHub Code Scanning
    if: inputs.importGitHub == 'true'
    uses: github/codeql-action/upload-sarif@v3
    with:
      sarif_file: report/qwiet-sarif-report-${{ github.repository_owner }}-${{ github.event.repository.name }}.sarif
      category: qwiet-prezero