name: Qwiet preZero

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    permissions:
      contents: read # Required for actions/checkout to fetch code
      security-events: write # Required for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # Needed in private repositories for github/codeql-action/upload-sarif

    runs-on: ubuntu-latest
    container: shiftleft/core:latest
    steps:
      - name: Checkout repository  # This is necessary to access your code
        uses: actions/checkout@v4
      - uses: ./